sudo: false
language: node_js
node_js:
    - "0.12"
    - "4"
    - "5"
before_script:
    - npm install -g npm
    - npm install -g grunt-cli
script:
    - "npm test"
notifications:
    irc:
        channels:
            - "irc://irc.freenode.org/##ohanami"
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
            - "Build details : %{build_url}"
